pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            steps {
                dir('bugtracker-backend') {
                    got test -v ./...
                }
            }
        }
    }
}